name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      coverage-directories: "src,ext"
    secrets: "inherit"
